// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using denemeclouddatabase.DATA;

#nullable disable

namespace denemeclouddatabase.DATA
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240320190021_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("denemeclouddatabase.DATA.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            Name = "John",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            Name = "Jane",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            Name = "Michael",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            Name = "Emily",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            Age = 32,
                            Name = "James",
                            Surname = "Wilson"
                        },
                        new
                        {
                            Id = 6,
                            Age = 29,
                            Name = "Emma",
                            Surname = "Jones"
                        },
                        new
                        {
                            Id = 7,
                            Age = 31,
                            Name = "William",
                            Surname = "Taylor"
                        },
                        new
                        {
                            Id = 8,
                            Age = 27,
                            Name = "Olivia",
                            Surname = "Anderson"
                        },
                        new
                        {
                            Id = 9,
                            Age = 33,
                            Name = "Alexander",
                            Surname = "Thomas"
                        },
                        new
                        {
                            Id = 10,
                            Age = 26,
                            Name = "Sophia",
                            Surname = "Martinez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
